Added a few more html tags
khalyomede/mantis pull request #6
Opened 2024-12-29 21:25 UTC by aminnairi

2024-12-29 21:49 UTC, khalyomede requested changes
You're a legend thanks @aminnairi :pray: 

I litteraly learned new elements, some of them are actually better than pulling KB of JS for tooltips :laughing: 

I just added comments to turn some elements into orphan and we're good to go thanks a lot again for this big job :rocket:

2024-12-29 21:49 UTC, khalyomede commented on html/br.v
> +}
Let's make it an orphan

```suggestion
pub fn br(attributes map[string]AttributeValue) string {
    return anon("br", attributes, [], true)
}
```

2024-12-29 21:49 UTC, khalyomede commented on html/col.v
> +}
Let's make it an orphan

```suggestion
pub fn col(attributes map[string]AttributeValue) string {
    return anon("col", attributes, [], true)
}
```

2024-12-29 21:49 UTC, khalyomede commented on html/img.v
> +}
Let's make it an orphan

```suggestion
pub fn img(attributes map[string]AttributeValue) string {
    return anon("img", attributes, [], true)
}
```

2024-12-29 21:49 UTC, khalyomede commented on html/input.v
> +}
Let's make it an orphan

```suggestion
pub fn input(attributes map[string]AttributeValue) string {
    return anon("input", attributes, [], true)
}
```

2024-12-29 21:49 UTC, khalyomede commented on html/meta.v
> +}
Let's make it an orphan

```suggestion
pub fn meta(attributes map[string]AttributeValue) string {
    return anon("meta", attributes, [], true)
}
```

2024-12-29 21:49 UTC, khalyomede commented on html/param.v
> +}
Let's make it an orphan

```suggestion
pub fn param(attributes map[string]AttributeValue) string {
    return anon("param", attributes, [], true)
}
```

2024-12-29 21:49 UTC, khalyomede commented on html/source.v
> +}
Let's make it an orphan

```suggestion
pub fn source(attributes map[string]AttributeValue) string {
    return anon("source", attributes, [], true)
}
```

2024-12-29 21:49 UTC, khalyomede commented on html/track.v
> +}
Let's make it an orphan

```suggestion
pub fn track(attributes map[string]AttributeValue) string {
    return anon("track", attributes, [], true)
}
```

2024-12-29 21:49 UTC, khalyomede commented on html/wbr.v
> +}
Let's make it an orphan

```suggestion
pub fn wbr(attributes map[string]AttributeValue) string {
    return anon("wbr", attributes, [], true)
}
```

2024-12-30 08:59 UTC, aminnairi commented
I might have already done the changes you suggested as you wrote them, you can check again if it satisfies your end goal.

2024-12-30 11:26 UTC, khalyomede commented
I just saw your changes thanks a lot! Since none of the orphans accept children, can you also remove the "children" parameter for these ones please? I have put the desired code in the suggested codes.

After that were good to merge 🚀

2024-12-30 12:11 UTC, merged